# Generated by Django 4.2.17 on 2025-01-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='size',
            field=models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], max_length=10),
        ),
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(choices=[('Non-Profit', 'Non-Profit'), ('Profit', 'Profit'), ('Government', 'Government'), ('Educational', 'Educational'), ('Healthcare', 'Healthcare')], max_length=20),
        ),
    ]
